FROM continuumio/anaconda3:2020.02

RUN easy_install xlsx2csv && \
  pip install csvkit && \
  apt install jq nginx -y

COPY ./covid_data_scrape.sh .
COPY ./xlsx2json.sh .
COPY ./index.docker.html /var/www/html/index.html

CMD ./covid_data_scrape.sh /var/www/html ; ./xlsx2json.sh /var/www/html ; $(which nginx) -c /etc/nginx/nginx.conf -g "daemon off;"
